# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('link', models.URLField(max_length=2083, unique=True, verbose_name='Link')),
                ('description', models.TextField(default='', help_text='A short description.  Please limit to 300 cahracters.', verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('ghost', models.BooleanField(default=False, verbose_name='Ghost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
