# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=2083, unique=True, verbose_name='URL'),
        ),
    ]
